"""OddsNameResolver — EXPLICIT team-name bridging for odds providers.

Why explicit and not fuzzy: the Espanyol/Barcelona incident. A fuzzy matcher
once folded "RCD Espanyol de Barcelona" onto Barcelona's row and silently gave
Espanyol another club's rating. A MISSING odds quote costs us nothing (the
fixture just ships unanchored, exactly as today); a WRONG one anchors a
prediction to a different club's price. So this module never guesses:

1. an explicit alias table (``config/odds_team_aliases.yaml``) wins;
2. the existing, already-verified ``data/club_name_map.json`` bridge is used
   next (that file is generated by the seeder from real fixtures);
3. a name that is already canonical passes through;
4. anything else returns ``None`` -> the caller SKIPS the fixture and logs it.

"Canonical" here is the dataset name space used everywhere else in the club
stack: ``normalize()``-ed football-data.co.uk historical names ("ath madrid",
"paris sg", "nott m forest"), which is what the Dixon-Coles params and the
Glicko ratings are keyed by.

Pure: no network, no DB.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from pathlib import Path

import yaml

from betbot.exchanges.matcher import normalize


class AliasTableError(ValueError):
    """An alias points at a name that is not canonical, or collides."""


class OddsNameResolver:
    """Resolve a provider's team spelling to a canonical dataset name."""

    def __init__(
        self,
        canonical: Iterable[str],
        *,
        aliases: Mapping[str, Iterable[str]] | None = None,
        name_map: Mapping[str, str] | None = None,
        strict: bool = True,
    ) -> None:
        self._canonical: set[str] = {normalize(c) for c in canonical if c}
        # normalised football-data.org name -> normalised dataset name.
        self._name_map: dict[str, str] = {
            normalize(k): normalize(v) for k, v in (name_map or {}).items()
        }
        self._canonical |= set(self._name_map.values())

        self._aliases: dict[str, str] = {}
        for canon, alts in (aliases or {}).items():
            canon_n = normalize(canon)
            if strict and self._canonical and canon_n not in self._canonical:
                raise AliasTableError(
                    f"alias target {canon!r} ({canon_n!r}) is not a canonical "
                    "team name — refusing to load a table that could point a "
                    "fixture at a club we cannot verify"
                )
            for alt in alts:
                alt_n = normalize(alt)
                prior = self._aliases.get(alt_n)
                if prior is not None and prior != canon_n:
                    raise AliasTableError(
                        f"alias {alt!r} maps to both {prior!r} and {canon_n!r}"
                    )
                self._aliases[alt_n] = canon_n

    # -- construction ---------------------------------------------------
    @classmethod
    def from_files(
        cls,
        alias_path: Path | str,
        name_map_path: Path | str,
        *,
        extra_canonical: Iterable[str] = (),
        strict: bool = True,
    ) -> "OddsNameResolver":
        """Build from ``config/odds_team_aliases.yaml`` + the club name map.

        Both files are optional: a missing/unreadable file degrades to an empty
        table, which means "resolve only exact canonical names" — safe.
        """
        aliases = _load_alias_yaml(Path(alias_path))
        name_map = _load_name_map(Path(name_map_path))
        return cls(
            canonical=list(name_map.values()) + list(extra_canonical),
            aliases=aliases,
            name_map=name_map,
            strict=strict,
        )

    # -- resolution -----------------------------------------------------
    def resolve(self, raw: str) -> str | None:
        """Canonical dataset name, or ``None`` when we cannot be sure.

        ``None`` is a first-class, safe answer: the caller must skip anchoring
        for that fixture and log the unresolved spelling so an alias can be
        added deliberately.
        """
        if not raw or not raw.strip():
            return None
        n = normalize(raw)
        if not n:
            return None
        hit = self._aliases.get(n)
        if hit is not None:
            return hit
        hit = self._name_map.get(n)
        if hit is not None:
            return hit
        if n in self._canonical:
            return n
        return None

    @property
    def canonical_names(self) -> frozenset[str]:
        return frozenset(self._canonical)

    @property
    def alias_pairs(self) -> dict[str, str]:
        return dict(self._aliases)


def _load_alias_yaml(path: Path) -> dict[str, list[str]]:
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError):
        return {}
    table = raw.get("aliases") if isinstance(raw, dict) else None
    if not isinstance(table, dict):
        return {}
    out: dict[str, list[str]] = {}
    for canon, alts in table.items():
        if isinstance(alts, str):
            alts = [alts]
        if isinstance(alts, list):
            out[str(canon)] = [str(a) for a in alts]
    return out


def _load_name_map(path: Path) -> dict[str, str]:
    import json

    try:
        d = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    if not isinstance(d, dict):
        return {}
    return {str(k): str(v) for k, v in d.items()}
